### ISSUE TITLE
How can we implement overlapping clusters in this module?

### ISSUE THREAD

**Issue by ManishSahu53** [srivathsanmurali/domsetLibrary#5]
I wanted to use this module to get overlapping clusters of sfm(openMVG). Can you please suggest me how to do it? or is there any other library to do it?

**Comment by pmoulon** [comment]
You can add a post processing step that add some neighborhing camera.
Or you can read the paper and extend the existing code:
Mauro, Massimo, et al. ["An integer linear programming model for view selection on overlapping camera clusters."](http://www.vision.ee.ethz.ch/~rhayko/paper/3dv2014_mauro_joint_selection_clustering.pdf) 2014 2nd International Conference on 3D Vision. Vol. 1. IEEE, 2014.

Mauro, Massimo, et al. ["Overlapping camera clustering through dominant sets for scalable 3D reconstruction."](http://www.vision.ee.ethz.ch/~rhayko/paper/bmvc2013_mauro_view_clustering.pdf) 2013 British Machine Vision Conference.

**Comment by srivathsanmurali** [comment]
I have been meaning to work on it for a while. Just been a bit busy with other projects at work. I could try getting it out soon.
I will update in a couple of days on how it goes.

**Comment by srivathsanmurali** [comment]
This is the same as a previous issue #4.

**Comment by ManishSahu53** [comment]
Thanks
@pmoulon @srivathsanmurali
